version: '3.8'
services:
  postgres:
    image: postgres:17
    container_name: cinema_postgres
    environment:
      POSTGRES_DB: cinema_db
      POSTGRES_USER: newuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U newuser -d cinema_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: cinema_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
  app:
    image: my-java-app:latest
    container_name: cinema_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cinema_postgres:5432/cinema_db
      SPRING_DATASOURCE_USERNAME: newuser
      SPRING_DATASOURCE_PASSWORD: mypassword
      SPRING_FLYWAY_USER: newuser
      SPRING_FLYWAY_PASSWORD: mypassword
    ports:
      - "7070:7070"
    depends_on:
      postgres:
        condition: service_healthy
volumes:
  pgdata:
  pgadmin-data: