spring:
  application:
    name: cinema
    version: 1.0.0
  datasource:
    username: newuser
    password: mypassword
    url: jdbc:postgresql://localhost:5432/cinema_db
  flyway:
    default-schema: public
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    schemas: public
    locations: classpath:db/migration
    baseline-on-migrate: true
    out-of-order: true
    clean-on-validation-error: false
  logging:
    level:
      org.flywaydb: DEBUG
      org.springframework.jdbc: DEBUG
server:
  port: 6060
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  version: 1.0.0
  packages-to-scan: com.psu.cinema.controller
  paths-to-match: /api/**