spring:
  application:
    name: cinema
    version: 1.0.0
  datasource:
    username: myuser
    password: mypassword
    url: jdbc:postgresql://localhost:5432/cinema_db
  flyway:
    default-schema: public
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    schemas: public
    locations: classpath:db/migration